project: 
  type: website
  
website: 
  page-navigation: true
  title: "Data Management & Storage Best Practices for Long-term and Archival Passive Acoustic Monitoring (PAM) Data" 
  site-url: "https://rwscollab.github.io/pam-data-mgmt/" 
  repo-url: https://github.com/RWSCollab/pam-data-mgmt 
  repo-actions: [edit, issue]
  
  page-footer:
    left: "&copy; CC-By RWSC Marine Mammal Subcommittee, 2022"
    right: 🐋
  
  search:
    location: sidebar
    type: textbox
    
  sidebar:
    title: PAM Data Management Best Practices
    logo: "images/MM.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://rwsc.org
        text: "rwsc.org"
      - icon: github
        href: https://github.com/RWSCollab/pam-data-mgmt
        text: "PAM Data Management"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: planning.qmd
        text: Planning Steps
      - href: deployment-data.qmd
        text: Deployment & Data Collection


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
